#!/bin/bash

set -e

cd spire

kubectl create ns spire
sleep 2

# Create the server’s service account, configmap and associated role bindings
kubectl apply \
    -f server-account.yaml \
    -f spire-bundle-configmap.yaml \
    -f server-cluster-role.yaml

# Deploy the server configmap and statefulset
kubectl apply \
    -f server-configmap.yaml \
    -f server-statefulset.yaml \
    -f server-service.yaml

# Configuring and deploying the SPIRE Agent
kubectl apply \
    -f agent-account.yaml \
    -f agent-cluster-role.yaml

sleep 2

kubectl apply \
    -f agent-configmap.yaml \
    -f agent-daemonset.yaml

# Applying SPIFFE CSI Driver configuration
kubectl apply -f spiffe-csi-driver.yaml

kubectl wait pod spire-server-0 -n spire --timeout=-1s --for=condition=ready
kubectl wait pod -n spire -l app=spire-agent --for=condition=ready