#!/bin/bash

if [[ -z $1 ]]; then
    echo "Error: please specify platform ('macos', or 'linux')"
    exit 1;
fi

if [ "$1" = "macos" ]; then
    wget -c https://github.com/istio/istio/releases/download/1.14.0-alpha.0/istioctl-1.14.0-alpha.0-osx.tar.gz -O - | tar -xz
fi

if [ "$1" = "linux" ]; then
    wget -c https://github.com/istio/istio/releases/download/1.14.0-alpha.0/istio-1.14.0-alpha.0-linux-amd64.tar.gz -O - | tar -xz
fi
